# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Deps
      run: yarn
    - name: Lint
      run: yarn run lint
    - name: Build
      run: NODE_ENV=production yarn run package
    - name: Test
      run: yarn test
    - name: Archive pbiviz
      uses: actions/upload-artifact@v2
      with:
        name: pbiviz
        path: dist/essex.cardbrowser.pbiviz